name: Build AAR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Download Gradle directly
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          mv gradle-8.7 gradle

      - name: Build with Gradle (no cache)
        run: ./gradle/bin/gradle :gadha_bridge:assembleRelease --no-build-cache

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: plugin-aar
          path: gadha_bridge/build/outputs/aar/*.aar
