name: Build AAR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload AAR
      uses: actions/upload-artifact@v3
      with:
        name: plugin-aar
        path: gadha_bridge/build/outputs/aar/*.aar
