name: Create Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  make-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download gradle 8.7
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          mv gradle-8.7 gradle

      - name: Make Gradle executable
        run: chmod +x ./gradle/bin/gradle

      - name: Generate wrapper files
        run: ./gradle/bin/gradle wrapper --gradle-version 8.7

      - name: Commit wrapper files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper || true
          git commit -m "chore: add gradle wrapper" || echo "no changes"
          git push origin HEAD:main
