name: Create Gradle Wrapper Safely

on:
  workflow_dispatch:

jobs:
  make-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create temp project and generate wrapper
        run: |
          mkdir tmpgradle
          cat > tmpgradle/settings.gradle <<'EOF'
rootProject.name = 'tmpgradle'
EOF
          cat > tmpgradle/build.gradle <<'EOF'
task wrapperTask {
    doLast {
        println 'noop'
    }
}
EOF
          # download gradle distribution and unzip (so we can run its wrapper task to generate wrapper files)
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          mv gradle-8.7 gradle
          chmod +x ./gradle/bin/gradle
          # run wrapper generation inside the minimal temp project so project-specific configuration is not evaluated
          ./gradle/bin/gradle -p tmpgradle wrapper --gradle-version 8.7

      - name: Copy wrapper files into repo
        run: |
          cp tmpgradle/gradlew . || true
          cp tmpgradle/gradlew.bat . || true
          mkdir -p gradle/wrapper
          cp tmpgradle/gradle/wrapper/gradle-wrapper.jar gradle/wrapper/ || true
          cp tmpgradle/gradle/wrapper/gradle-wrapper.properties gradle/wrapper/ || true
          # If tmpgradle didn't create gradle/wrapper files (older gradle behavior), create a properties file matching 8.7:
          if [ ! -f gradle/wrapper/gradle-wrapper.properties ]; then
            cat > gradle/wrapper/gradle-wrapper.properties <<'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
EOF
          fi
          chmod +x gradlew || true
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle || true
          git commit -m "chore: add gradle wrapper" || echo "no changes"
          git push origin HEAD:main || echo "push failed"
